### ISSUE TITLE
GDB.ZIP (.Zip) automatically starts downloading. I want to prevent downloading....

### ISSUE THREAD

**Issue by abdulrehmanch112** [calvinmetcalf/leaflet.filegdb#2]
![shp](https://cloud.githubusercontent.com/assets/8075814/3487000/c6910ec0-045d-11e4-9392-46f29f43e360.PNG)

**Comment by lalprakash** [comment]
@abdulrehmanch112 Did you solve this issue? I'm greatly in need of this.. The shapefile just downloads instead of displaying in the map.

@calvinmetcalf Please help me to solve this issue. I'm using leaflet.shapefile to display a shapefile in my map. The shapefile just downloads by default instead of displaying in the map.

**Comment by calvinmetcalf** [comment]
see https://github.com/calvinmetcalf/leaflet.shapefile/issues/11#issuecomment-305253771
